FROM pytorchlightning/pytorch_lightning

# install required packages
RUN pip install numpy
RUN pip install pandas
RUN pip install matplotlib
RUN pip install scikit-learn
RUN pip install torchvision
RUN pip install tensorboard
