FROM continuumio/miniconda

# install packages
RUN conda install -c conda-forge numpy
RUN conda install -c conda-forge scikit-learn
RUN conda install python==3.9 pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 -c pytorch
RUN conda install -c conda-forge cudatoolkit=11.1 
RUN conda install lightning=1.5 -c conda-forge
RUN conda install -c anaconda pandas
RUN conda install -c conda-forge matplotlib
RUN conda install -c conda-forge pillow